In [2]:
#Exercice 1

import numpy as np
def somme(A,B):
    if (A.shape == B.shape):
        C = A + B
        print(C)
    else:
        print("Impossible d'additionner")
        

A = np.array([[1,3,8],[-3,6,8],[-6,7,8]])
B = np.array([[6,7,5],[1,2,3],[5,6,7]])
somme (A,B)

[[ 7 10 13]
 [-2  8 11]
 [-1 13 15]]


In [24]:
#Exerice 2

def produit(A,B):
    print("A :",A.shape[1])
    print("b:",B.shape[0])
    if(A.shape[1] == B.shape[0]):
        C = A.dot(B)
        print(C)
    else:
        print("Impossible de multiplier")

C = np.array([[1,3,8],[-3,6,8],[-6,7,8]])
D = np.array([[6,7,5],[1,2,3],[5,6,7]])

produit(C,D)


A : 3
b: 2
Impossible de multiplier


In [50]:
#Exercice 3

def estStochastique(A):
    estStochastique = True;
    if A.shape[1]!=A.shape[0]:
        estStochastique = False;
    else:
        for i in range(A.shape[0]):
            s=np.sum(A[i])
            if s != 1:
                estStochastique = False
                break
    return estStochastique

def estBistochastique(A):
    estBistochastique = True;
    if estStochastique(A)==False:
        estBistochastique = False;
    else:
        for i in range(A.shape[0]):
            s=np.sum(A[:,i])
            if s != 1:
                estBistochastique = False
                break
    return estBistochastique   

        

E = np.array([[0.1,0.7,0.2], [0.5,0.3,0.2], [0,0.8,0.2]])

# === Stochastique ===
res = estStochastique(E)
#Affichage en clair
if(res):
    print("La matrice est stochastique")
else:
    print("La matrice n'est pas stochastique")

# === Bistochastique ===
F = np.array([[1/3,1/3,1/3],[1/3,1/3,1/3],[1/3,1/3,1/3]])
res = estBistochastique(F)
#Affichage en clair
if(res):
    print("La matrice est Bistochastique")
else:
    print("La matrice n'est pas Bistochastique") 


La matrice est stochastique
La matrice est Bistochastique


In [51]:
# Exercice 4

import numpy as np

def transposer(A):
    print(np.transpose(A))

G = np.array([[1,3,8],[-3,6,8],[-6,7,8]])
transposer(G)

[[ 1 -3 -6]
 [ 3  6  7]
 [ 8  8  8]]
